BAU add ability to freeze package lock via repo env (#1442)

diff --git a/.github/workflows/_run-node-install-and-compile.yml b/.github/workflows/_run-node-install-and-compile.yml
--- a/.github/workflows/_run-node-install-and-compile.yml
+++ b/.github/workflows/_run-node-install-and-compile.yml
@@ -25,6 +25,25 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
+      - name: Check if package-lock.json is frozen
+        if: github.event_name == 'pull_request'
+        env:
+          FREEZE_PACKAGE_LOCK: ${{ vars.FREEZE_PACKAGE_LOCK }}
+        run: |
+          if [[ "$FREEZE_PACKAGE_LOCK" == "true" ]]; then
+            echo "package lock freeze is enabled. evaluating..."
+
+            git fetch origin ${{ github.base_ref }}
+            CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}..HEAD)
+
+            if echo "$CHANGED_FILES" | grep -q "^package-lock\.json$"; then
+              echo "🧊 ERROR: package-lock.json has been modified but FREEZE_PACKAGE_LOCK is set to true"
+              echo "revert changes to package-lock.json or disable the freeze by setting FREEZE_PACKAGE_LOCK to false"
+              exit 1
+            else
+              echo "✅ no changes detected in package-lock.json"
+            fi
+          fi
       - name: Setup
         uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
         with:
